AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Automatic database shut down and start up Lambda functions
Parameters:
  InstanceID:
    Type: String
    Default: testdb
  InstanceARN:
    Type: String
    Default: arn:aws:rds:ap-southeast-2:123456789012:db:testdb
Globals:
  Function:
    MemorySize: 128
    Timeout: 3
    Handler: app.lambdaHandler
    Runtime: nodejs12.x
    Environment:
      Variables:
        INSTANCE_IDENTIFIER:
          Ref: InstanceID
Resources:
  DBShutDownFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://auto-aws-db-shutdown-deployment-artifacts-bucket/ce5a18943bd319014d6e8c1bd3be393e
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - rds:StopDBInstance
          Resource:
            Ref: InstanceARN
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 17 ? * MON-FRI *)
      DeadLetterQueue:
        Type: SNS
        TargetArn:
          Ref: DBFunctionsDeadLetterTopic
  DBStartUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://auto-aws-db-shutdown-deployment-artifacts-bucket/d31b171ea79cbf6bca71eeb99f1acfaf
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - rds:StartDBInstance
          Resource:
            Ref: InstanceARN
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 ? * MON-FRI *)
      DeadLetterQueue:
        Type: SNS
        TargetArn:
          Ref: DBFunctionsDeadLetterTopic
  DBFunctionsDeadLetterTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: terrence.miao@paradise.org
        Protocol: email
