version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-typescript-webpack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qfxu9y982ao"
s3_prefix = "sam-typescript-webpack"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
