Serverless Lambda Step Functions
================================

This is an example of creating, deploying and invoking AWS Lambda Function which calls a Step Functions.

Prerequisites
-------------

- Have AWS access and secret key available through a provided method, in `~/.aws/config` and `~/.aws/credentials` files
- Node.js  for example `12.x`
- **serverless CLI** installed by running `sudo npm install -g serverless`

Dependencies
------------

By running `npm install`

Deploy
------

By running `sls deploy -v`:

[source.console]
----
terrence@igloo ~/Projects/AWS/serverless-lambda-step-functions (master ⚡↩☡=)
𝜆 sls deploy -v
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-lambda-step-functions-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - serverless-lambda-step-functions-dev
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service serverless-lambda-step-functions.zip file to S3 (10.28 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-lambda-step-functions-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - HelloWorldLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CiaoWorldLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ProxyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - HelloWorldStepFunctionsRole
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - HelloWorldStepFunctionsRole
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ProxyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CiaoWorldLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ProxyLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - HelloWorldLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CiaoWorldLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - HelloWorldLogGroup
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - HelloWorldStepFunctionsRole
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::StepFunctions::StateMachine - HelloWorldStepFunctions
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - HelloWorldLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CiaoWorldLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CiaoWorldLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - HelloWorldLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - HelloWorldLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - CiaoWorldLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::StepFunctions::StateMachine - HelloWorldStepFunctions
CloudFormation - CREATE_COMPLETE - AWS::StepFunctions::StateMachine - HelloWorldStepFunctions
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloWorldLambdaVersionDOuMNTmqtp6xNSPR6bdfUatLb7EgbG6sX7P97KIZHY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CiaoWorldLambdaVersionmdeDDWmFPxMpZO1EAj7ji44zOBB2bzSqkiSvcNbMHjU
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ProxyLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloWorldLambdaVersionDOuMNTmqtp6xNSPR6bdfUatLb7EgbG6sX7P97KIZHY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - CiaoWorldLambdaVersionmdeDDWmFPxMpZO1EAj7ji44zOBB2bzSqkiSvcNbMHjU
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - HelloWorldLambdaVersionDOuMNTmqtp6xNSPR6bdfUatLb7EgbG6sX7P97KIZHY
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - CiaoWorldLambdaVersionmdeDDWmFPxMpZO1EAj7ji44zOBB2bzSqkiSvcNbMHjU
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ProxyLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - ProxyLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ProxyLambdaVersionqvaMgxePZldsrGNqhyxQfJrKPveUZDVT8qWErmDqY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ProxyLambdaVersionqvaMgxePZldsrGNqhyxQfJrKPveUZDVT8qWErmDqY
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - ProxyLambdaVersionqvaMgxePZldsrGNqhyxQfJrKPveUZDVT8qWErmDqY
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-lambda-step-functions-dev
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - serverless-lambda-step-functions-dev
Serverless: Stack update finished...
Service Information
service: serverless-lambda-step-functions
stage: dev
region: ap-southeast-2
stack: serverless-lambda-step-functions-dev
resources: 14
api keys:
  None
endpoints:
  None
functions:
  helloWorld: serverless-lambda-step-functions-dev-helloWorld
  ciaoWorld: serverless-lambda-step-functions-dev-ciaoWorld
  proxy: serverless-lambda-step-functions-dev-proxy
layers:
  None

Stack Outputs
HelloWorldLambdaFunctionQualifiedArn: arn:aws:lambda:ap-southeast-2:123456789012:function:serverless-lambda-step-functions-dev-helloWorld:1
Proxy: arn:aws:states:ap-southeast-2:123456789012:stateMachine:HelloWorldStepFunctions
CiaoWorldLambdaFunctionQualifiedArn: arn:aws:lambda:ap-southeast-2:123456789012:function:serverless-lambda-step-functions-dev-ciaoWorld:1
ProxyLambdaFunctionQualifiedArn: arn:aws:lambda:ap-southeast-2:123456789012:function:serverless-lambda-step-functions-dev-proxy:2
HelloWorldStepFunctionsArn: arn:aws:states:ap-southeast-2:123456789012:stateMachine:HelloWorldStepFunctions
ServerlessDeploymentBucketName: serverless-lambda-step-f-serverlessdeploymentbuck-imldcok3kgdq
----

Test
----

Invoke the Proxy Lambda by running `sls invoke -f proxy -l`:

[source.console]
----
𝜆 sls invoke -f proxy -l
null
--------------------------------------------------------------------
START RequestId: 9a53aea7-64cb-460c-96cc-69ec43ee853a Version: $LATEST
2020-12-22 01:18:13.235 (+11:00)	9a53aea7-64cb-460c-96cc-69ec43ee853a	INFO	started execution of step function
END RequestId: 9a53aea7-64cb-460c-96cc-69ec43ee853a
REPORT RequestId: 9a53aea7-64cb-460c-96cc-69ec43ee853a	Duration: 189.84 ms	Billed Duration: 190 ms	Memory Size: 1024 MB	Max Memory Used: 89 MB	Init Duration: 502.11 ms
----

Undeploy
--------

- Run `serverless remove`

References
----------
- Invoke AWS Step Function from AWS Lambda using the Serverless Framework, _https://medium.com/@iamNoah_/invoke-aws-step-function-from-aws-lambda-using-the-serverless-framework-21b7fde38a42_